export * from '../pages/create/create.component';
export * from '../pages/customers/customers.component';
export * from '../pages/goods/goods.component';
export * from '../pages/create/prod-card/prod-card.component';
export * from '../pages/goods/edit/edit.component';
export * from '../pages/goods/delete/delete.component';
export * from '../pages/order/order.component';
export * from '../pages/roles/roles.component';
export * from '../pages/roles/delete-message/delete-message.component';